name: los_iam_service

services:
  iam-service:
    container_name: iam-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      iam-mongo-db:
        condition: service_healthy
    networks:
      - loan-network

  iam-mongo-db:
    image: mongo:6.0
    container_name: iam-mongo-db
    ports:
      - "27019:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - loan-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  loan-network:
    name: los-network
    external: true

volumes:
  mongo-data:
    driver: local