# Spring configuration
spring:
  profiles:
    active: local
  application:
    name: iam-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
  mongodb:
    uri: ${MONGO_URI}

# Server port configuration
server:
  port: 4200

# API related configuration
api:
  base_url: /api/v1/auth

# Login configuration for user
login:
  max_attempt: 5
  lockout_in_minutes: 15

# Filter Level Configuration
filter:
  mdc:
    trace:
      header: X-Trace-Id
      key: traceId
    correlation:
      header: X-Correlation-Id
      key: correlationId
  rateLimiter:
    apiKey:
      header: X-API-KEY
    forwardedFor:
      header: X-Forwarded-For
    retryAfter:
      header: Retry-After
      seconds: 60
    bucket:
      capacity: 500
      refill: 500
      intervalInMinutes: 1
      cache:
        maxSize: 10000
        expiresAfterHour: 1

# Thread level Configuration for Async Processing
threadConfig:
  async:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 500
    threadNamePrefix: "iam-async-"

# Security configuration
security-config:
  cors:
    allowed_origins:
      - "http://localhost:4200"
    allowed_methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed_headers:
      - "Authorization"
      - "Content-Type"
      - "Cache-Control"
      - "X-Requested-With"
    exposed_headers:
      - "Authorization"
    allow_credentials: true
    max_age: 3600

app:

  base-url: http://localhost:5600/api/v1/auth

  token:
    refresh_token:
      expiry_in_days: 30
    activation_token:
      expiry_in_hours: 24
    reset_token:
      expiry_in_hours: 20

info:
  app:
    name: ${spring.application.name}
    description: "Service to manage identity and access"
    version: 1.0.0
  base_url: "/api/v1/auth"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

  metadata:
    issuer: ${spring.application.name}
    expiration_in_minutes: 30

#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_HOST}:8761/eureka/