iam:
  security:
    cors:
      allowed_origins:
        - "http://localhost:4200"  # Angular UI
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - "Authorization"
        - "Content-Type"
        - "Cache-Control"
        - "X-Requested-With"
      exposed_headers:
        - "Authorization"
      allow_credentials: true
      max_age: 3600